### PR TITLE
[ts] Fixes to Order line item and tax line typings (#367)

### LINKED ISSUE #367: Incorrect line item type definitions
There are some mistakes in the line item type definitions.
For refund line items:
* `product_id` is marked as non-null
* `requires_shipping` is incorrectly named as `require_shipping`
* `tip_payment_gateway` and `tip_payment_method` are marked as always being present

For order line items:
* `discount_allocations` is missing
* `fulfillment_status` is given the values of order fulfillment states rather than line item ones
* `tip_payment_gateway` and `tip_payment_method` are missing
* `variant_id` is marked as nullable

### PR DESCRIPTION
**Pull request by tkalliom**
Fixes #367. The typings have had separate types `ILineItem`, for the `line_item` property of refund line items, and `IOrderLineItem`, for the `line_items` property of orders. Both typings have some issues, as detailed in the bug report. As the refund `line_item` is specified in the API documentation using a reference to order line items, this commit removes the former type in favor of the latter to reflect the specification.

Also fixes order tax lines being typed with the `price_set` property, which only exists on line item level tax lines.

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -2038,7 +2010,6 @@ declare namespace Shopify {
   interface IOrderTaxLine {
     title: string;
     price: string;
-    price_set: IOrderAdjustmentAmountSet;
```
Comment (lpinca) [inline index.d.ts:2041]: Added in https://github.com/MONEI/Shopify-api-node/commit/f71a10a3b588d1e889d792188dcc498d1afa301e I don't think it should be removed.

File: index.d.ts [hunk 2]
```diff
@@ -2060,14 +2032,16 @@ declare namespace Shopify {
     requires_shipping: boolean;
     sku: string;
     title: string;
-    variant_id: number | null;
```
Comment (lpinca) [inline index.d.ts:2063]: `null` was added in https://github.com/MONEI/Shopify-api-node/commit/b3b34ccf4f92e8292096c8660793c47922599f83 I think it should not be removed.

File: index.d.ts (hunk 1 above)
Comment (tkalliom) [reply index.d.ts:2041]: At that time, this `IOrderTaxLine` type was used for both order-level `tax_lines` (which don’t have `price_set`) and item-level `tax_lines` (which do have `price_set`). This change reorganizes types so that this is only used for order-level ones, so this should not have `price_set`.

File: index.d.ts (hunk 2 above)
Comment (tkalliom) [reply index.d.ts:2063]: I relied on the documentation too much. It’s not mentioned at https://shopify.dev/docs/admin-api/rest/reference/orders/order#line-items-property-2020-01 but according to https://community.shopify.com/c/Shopify-APIs-SDKs/Orders-line-item-variant-id-fields-are-null/td-p/130401 yes, this can be `null`

**Comment by lpinca** [comment]
Thank you.
